name: schemas-validation-workflow

run-name: ${{ github.actor }} is validating the JSON schemas

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check-jsonschema:
  
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install check-jsonschema tool
        run: pip install check-jsonschema
        
      - name: Validate API Label schema
        run: check-jsonschema -v --schemafile api-label.jschema ./data/api-label-instance.json
        
      - name: Validate App Label schema
        run: check-jsonschema -v --schemafile app-label.jschema ./data/app-label-instance.json

      - name: Validate WP3 Commands schema
        run: check-jsonschema -v --schemafile wp3-commands.jschema ./data/wp3-commands-instance1.json ./data/wp3-commands-instance2.json ./data/wp3-commands-instance3.json

      - name: Validate WP3 Log Message schema
        run: check-jsonschema -v --schemafile wp3-log-message.jschema ./data/wp3-log-message-instance1.json ./data/wp3-log-message-instance2.json

      - name: Validate WP3 Response Data schema
        run: check-jsonschema -v --schemafile wp3-response-data.jschema ./data/wp3-response-data-instance1.json ./data/wp3-response-data-instance2.json ./data/wp3-response-data-instance3.json

