name: schemas-validation-workflow
run-name: ${{ github.actor }} is validating the JSON schemas
on: [push]
jobs:
  validate-API-label-schema:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install check-jsonschema
      - run: check-jsonschema -v --schemafile api-label.jschema ./data/api-label-instance.json
      - run: check-jsonschema -v --schemafile app-label.jschema ./data/api-label-instance.json
